### PR TITLE
first login page complete, made changes to template and app.js as well

### PR DESCRIPTION
**Pull request by Rubix982**
# Issue Type

### Please select the type of changes this PR has and add some context.

🏆 Enhancements

Add `first login` page as complete.

# To do after Pull Request is accepted

Always remember to pull changes in your main after a PR has been accepted to reflect the new changes!

### CODE REVIEW

**Comment by Rubix982** [comment]
I made the left component `scrollable`. Try this out by increasing your page size from 100% to 120% or more. The left increases with the increase in size, but becomes scrollable so the details aren't lost and you can still navigate. The right image stays fixed and DOES NOT grow - absolute positioning.

**Comment by hassanzhd** [comment]
Is this PR complete?

**Comment by Rubix982** [comment]
@hassanzhd no, work is still left to be done. I'll work on it tomorrow after I'm done with my assignments.

**Comment by hassanzhd** [comment]
Okay!

**Comment by Rubix982** [comment]
Merging, closing, and deleting this PR and opening another. There is a pull problem that git can't solve, for some reason.
image

**Pull request merged**
